### ISSUE TITLE
Login via Email/Password 401 Erroring on GuiInit branch & Moxie server

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#107]
## Problem
Unable to login via email/password on both the Moxie and Gui-Init branches via VS Code & Windows/Mac.

### Steps to reproduce
Attempt to login

### Environment
Chrome
VSCode
Moxie

*Subheadings below are optional; remove if not applicable.*
### Location
Home Page Login N/A

## Behavior
Login Fails, no response of failure only in console log do you see the response
### Expected behavior
Login should pass
### Observed behavior
Nothing occurs but you can see the 401 Error

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
*Relevant console output or errors, pasted as text.*

### Screenshot
![image](https://github.com/user-attachments/assets/21eb23c7-c788-4ab5-acd0-1f18b6234085)

## Other notes
Applying on both Moxie Server and VsCode individual branches

*Remember to assign the issue exactly one severity label.*

**Comment by PiesArentSquare** [comment]
the long awaited fix by e09a092ef6e92bd429ce94e2194af4031c016318

**Comment by SmartGarlic** [comment]
Huzzah!
