### ISSUE TITLE
Password Validation is Incorrectly validating.

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#108]
## Problem
*A clear description of the defect or bug.*
On filling in a password on the sign-up page, the confirm password is matching the field above, however, if you backtrack to change the original password or modify it it still notes that it is correct despite being an incorrect password.

### Steps to reproduce
1. Enter first password
2. Enter second password
3. Go back to first password and remove any number of characters or make the passwords not match

### Environment
Chrome
Moxie Server
Gui-init

*Subheadings below are optional; remove if not applicable.*
### Location
http://moxie.cs.oswego.edu:49000/Registration 

## Behavior
Fields are still validated, though you cannot continue

### Expected behavior
Fields should invalidate

### Observed behavior
You cannot continue forward but users are unaware of the error in the event that they go backwards and forwards again for any reason

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
*Relevant console output or errors, pasted as text.*

### Screenshot
![image](https://github.com/user-attachments/assets/e8a9877c-b307-4c48-aebb-7bc65154d406)

**Comment by MSCompSci** [comment]
Opened a PR #126

**Comment by SmartGarlic** [comment]
Fixed!
