### ISSUE TITLE
Tasks can be created without assigning a name

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#110]
## Problem
Tasks can be created without a name.

### Steps to reproduce
Create a task without filling in the name field but filling in other fields.

### Environment
Chrome 
Moxie
Windows

*Subheadings below are optional; remove if not applicable.*
### Location
*URL(s) where the bug occurs.*
http://moxie.cs.oswego.edu:49000/

## Behavior
Tasks are created without a name and input into the cell array. This creates confusion for users as they would not know what the tasks are ahead of the time.

### Expected behavior
I should be unable to create a task without a name or feedback should be given to a user that the field is a required field.

### Observed behavior
No feedback is given to users. No error is given.

### Screenshot
![image](https://github.com/user-attachments/assets/3047a80b-b228-4d88-ad71-d61792d18eff)

*Top-level headings below are optional; remove if not applicable.*
## Suggested fix
Make task titles a required field to select save and notify users that they must complete this field or change a default select to the field when not filled in on selecting save.

**Comment by MSCompSci** [comment]
Just opened a PR that should fix this #125

**Comment by SmartGarlic** [comment]
Fixed!
