### ISSUE TITLE
Cannot Create Task with "No Priority" status (This status should just be removed and a default status selected for all users)

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#111]
## Problem
*A clear description of the defect or bug.*

post: /tasks
response error 500:
Unable to deserialize property 'priority' because of: Error setting value on: model.Task@3b9fe842

### Steps to reproduce
Try to create a task with the priority status of "No Priority"

### Environment
Moxie
Vs Code
Gui-Init Branch Commit: d8aba03
Chrome

*Subheadings below are optional; remove if not applicable.*
### Location
http://moxie.cs.oswego.edu:49000/

## Behavior
When attempting to save a task with "No Priority" a task does not save.

### Expected behavior
Task should save with a priority of "No Priority"

### Observed behavior
Task does not save.

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
post: /tasks
response error 500:
Unable to deserialize property 'priority' because of: Error setting value on: model.Task@3b9fe842

### Screenshot
![image](https://github.com/user-attachments/assets/0ddbfff8-ace0-4e33-993c-26c841975efa)

## Suggested fix
Remove "No Priority" have "Low" priority set as the default priority for all tasks created and remove the ability for users to select anything other than Low/Medium/High.

**Comment by PiesArentSquare** [comment]
no priority now works correctly in c52d3b0c0d93015ed05ae03c22ec8244c5db0bac, although whether its needed/wanted is another story

**Comment by SmartGarlic** [comment]
Functioning now so closing the ticket, will bring up the point of no priority as a usability question.
