### ISSUE TITLE
Project and Description being removed post initial save of any Task

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#112]
## Problem
Whenever a task is saved and a description or project is assigned it is not stored. When you revisit the task the Description and Project are both removed. (Though the project is visible in the console, the field is not updated to the appropriate project)

### Steps to reproduce
Create a task with the description and project fields selected
Select off the task after it has been saved
Reselect the task

### Environment
Moxie
Vs Code
Chrome

*Subheadings below are optional; remove if not applicable.*
### Location
http://moxie.cs.oswego.edu:49000/

## Behavior
Description and Project are being removed. Project is only being removed from the visible field, description is removed entirely from the array.

### Expected behavior
Description and Project should re-appear when selecting a task from the project array.

### Observed behavior
Description and Project and being removed when selection is lost.

### Screenshot
![image](https://github.com/user-attachments/assets/921d97f8-993b-4e96-a062-5c90d83093ef)

**Comment by PiesArentSquare** [comment]
fixed in c52d3b0c0d93015ed05ae03c22ec8244c5db0bac

**Comment by SmartGarlic** [comment]
Fixed and working appropriately!
