### ISSUE TITLE
Task name doesn't sort correctly on any projects page

### ISSUE THREAD

**Issue by jbaile20** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#113]
## Problem
When sorting on any project page, the task description doesn't sort alphabetically 

### Steps to reproduce
- Add several tasks to a project with different lettered names
- try sorting by task name

### Environment
OS: Windows
Browser: Chrome
Branch: Gui-init (d8aba03)

*Subheadings below are optional; remove if not applicable.*
### Expected behavior
Correctly sorts alphabetically 
### Observed behavior
Doesn't sort alphabetically

*Subheadings below are optional; remove if not applicable.*
### Screenshot
![image](https://github.com/user-attachments/assets/ee29e4a4-0de5-41f3-ae6b-8dd0ac01f2eb)

*Top-level headings below are optional; remove if not applicable.*
## Other notes
**Task Names DO correctly sort on the My Tasks page, just not on any projects page**

*Remember to assign the issue exactly one severity label.*

**Comment by SmartGarlic** [comment]
On further examination of this it appears to be case sensitive. When a task is labeled "Bananas" vs "bananas", the lower case version will not sort correctly but the upper case will. Additionally this does not function on the My Tasks or Project pages.

**Comment by MSCompSci** [comment]
It turns out that this kind of sorting was due to the built-in sorting function used by the tanstack table library. The `alphanumeric` function was being used instead of the `alphanumericCaseSensitive` function that actually takes the case into account when sorting. I opened a PR that should fix this #127

**Comment by MSCompSci** [comment]
There were still issues with sorting even after changing to `alphanumericCaseSensitive`, but hopefully this PR should work #134

**Comment by jbaile20** [comment]
Yep, #134 seems to fix it. Thank you!
