### ISSUE TITLE
Previous Task Detail Panel exists underneath the new panel in "Projects" pages

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#114]
## Problem
The previous Task Panel from an older mock-up is still present underneath the Task Detail page.

### Steps to reproduce
Go to any project page and look to the right when a task detail page is up.

### Environment
Moxie
Chrome
Windows
VsCode
Gui-init Commit: d8aba03

*Subheadings below are optional; remove if not applicable.*
### Location
http://moxie.cs.oswego.edu:49000/project/1
http://moxie.cs.oswego.edu:49000/project/2
http://moxie.cs.oswego.edu:49000/project/3

## Behavior
Task Detail Panel appears with underlying original UI

### Expected behavior
Original UI should not exist

### Observed behavior
Original UI appears to be stored underneath new UI

### Screenshot
![image](https://github.com/user-attachments/assets/3acf1bf0-eae2-451c-a4fa-60a52f1c7dd8)

**Comment by PiesArentSquare** [comment]
either fixed by c52d3b0c0d93015ed05ae03c22ec8244c5db0bac, or had already been fixed

**Comment by SmartGarlic** [comment]
Solved and fixed! Thanks!
