### ISSUE TITLE
Cannot edit tasks

### ISSUE THREAD

**Issue by jbaile20** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#116]
## Problem
Cannot edit tasks, when trying to edit a task and save changes it creates an entirely new task instead

### Steps to reproduce
- Create a task and hit save changes
- re-select the same task and attempt to edit any field, and hit save changes
- notice a new task with a new ID is now present in the task table instead of changing the initial task information
### Environment
OS: Windows
Browser: Chrome
Branch: Gui-init (d8aba03)

*Subheadings below are optional; remove if not applicable.*
### Location
My Tasks page

### Expected behavior
The task is edited successfully and will update/show the changes in the My Tasks table _and_ on the right panel
### Observed behavior
An entirely new task is created instead

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
*Relevant console output or errors, pasted as text.*

### Screenshot
**Initial Task Creation called "Testing Task Edit"**
![image](https://github.com/user-attachments/assets/f665236a-dead-4421-bb50-a5b1755b4f6f)
After saving changes, new task is created
![image](https://github.com/user-attachments/assets/e1795e7f-8e32-41e3-b800-ed4a1806c143)

*Top-level headings below are optional; remove if not applicable.*
## Other notes

*Remember to assign the issue exactly one severity label.*

**Comment by PiesArentSquare** [comment]
fixed by c52d3b0c0d93015ed05ae03c22ec8244c5db0bac

**Comment by SmartGarlic** [comment]
Task changes are saved now on current pushed item! Woohoo!!
