### ISSUE TITLE
Unable to start frontend service on Mac OS

### ISSUE THREAD

**Issue by Danpmas** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#12]
## Problem
*A clear description of the defect or bug.*
Each step was completed successfully in the README file up until the "npm run dev" command. The frontend service could not be successfully executed and https://localhost:9443 could not be reached. The issue was replicated for both the most recent commit (commit hash 932df44ec67232859ebb2efbffe4bc497072b3b2) and the version Jeremiah provided in the QA channel (commit hash 56db95962bff4cb5ca6e0793f8da34b9b15be435).

### Steps to reproduce
- Change directory in terminal to "OZ-CSC-480-HCI-521-Fall-2024".
- Run "cd backend/auth-service
mvn liberty:start
cd ../database-service
mvn liberty:start
cd ../../frontend
npm i
npm run dev"

### Environment
*Browsers and operating systems on which the problem is known to occur.*
The operating system used for testing was a MacBook Pro. The browser used to attempt to reach local host was chrome. HOWEVER, on Windows, the "npm run dev" command executes without error and local host was accessed successfully.

*Subheadings below are optional; remove if not applicable.*
### Location
*URL(s) where the bug occurs.*
https://localhost:9443

### Expected behavior
"npm run dev" command runs without errors and local host can be accessed.

### Observed behavior
Error is thrown in terminal and "npm run dev" fails to execute.

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
The error produced:
"danmas@Dans-MacBook-Pro frontend % npm run dev

> frontend@0.0.0 dev
> vite

error when starting dev server:
Error: listen EACCES: permission denied ::1:80
    at Server.setupListenHandle [as _listen2] (node:net:1882:21)
    at listenInCluster (node:net:1961:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:2135:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:8)"

### Screenshot
*Shows the incorrect behavior.*
<img width="689" alt="Screenshot 2024-10-09 at 12 24 29 PM" src="https://github.com/user-attachments/assets/8da9caa5-5d19-40f3-b9d4-cf1b26adaec5">

*Top-level headings below are optional; remove if not applicable.*
## Suggested fix
Change the port number used since Mac OS seems to not be able to access port 80.

## Other notes
Three members of the QA Team replicated the error on Mac OS. Two members using windows successfully executed each command without error.

*Remember to assign the issue exactly one severity label.*

**Comment by PiesArentSquare** [comment]
this is caused because port 80 is already in use, we're working on getting some config set up so this can be easily changed

**Comment by PiesArentSquare** [comment]
added some configuration files so now port 80 can be changed with little hassle
