### ISSUE TITLE
Tasks unable to be created

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#140]
## Problem
Tasks are unable to be created

### Steps to reproduce
Try to create any task, anywhere

### Environment
Chrome

*Subheadings below are optional; remove if not applicable.*
### Location
[*URL(s) where the bug occurs.*](http://moxie.cs.oswego.edu:49000/)

### Expected behavior
On "Add a New Task" a task should appear

### Observed behavior
Information in the Task Details section remains and no task is created. 

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
Error adding new task:  SyntaxError: Failed to execute 'json' on 'Response': Unexpected end of JSON input
    at addEditTask (TaskSidePanel.jsx:44:41)

### Screenshot
![image](https://github.com/user-attachments/assets/db351872-6d74-4a0e-b7b8-218de94e6e91)

**Comment by PiesArentSquare** [comment]
fixed in e09a092ef6e92bd429ce94e2194af4031c016318
