### ISSUE TITLE
Password Icon is Reversed

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#141]
## Problem
When signing up for an account password visibility is the opposite of the icon's functionality. 

The Open Eye should show the password and the Closed Eye should hide the password.

### Steps to reproduce
Sign up for an account and look at the password visibility icons when information is in the field.
![image](https://github.com/user-attachments/assets/d1e8ef50-cee1-4431-99ae-7b2f0f38c6d3)

### Environment
Chrome

**Comment by MSCompSci** [comment]
Opened a PR to fix this #142
