### ISSUE TITLE
Registration, Login, and TaskPage Endpoint Issues

### ISSUE THREAD

**Issue by Danpmas** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#34]
## Problem
Could not create an account, login or access the task page. Also, loading the main login page will automatically trigger a 401 status error.

### Steps to reproduce
1. Add GitHub Client ID and Secret Key as environment variables
2. Change directory in terminal to "OZ-CSC-480-HCI-521-Fall-2024".
3. Can run commands in either setting, which reproduced the same result:
- Run in terminal "cd backend/auth-service
mvn liberty:start
cd ../database-service
mvn liberty:start
cd ../../frontend
npm I
npm run dev"
- Execute the "start_website" and "stop_website" scripts with the appropriate script for your OS.
4. Open a browser (both safari and chrome were tested) and paste "http://localhost:2080" which will automatically send the user to the login endpoint
5. Select the “DON’T HAVE AN ACCOUNT? SIGN UP” text (only the "SIGN UP" text sends the user to the registration page.
6. Add a username and password in the appropriate location, then select the "Sign Up" button.

For testing the task page endpoint:
1. Repeat steps 1-3
2. Open a browser and paste "http://localhost:2080/TaskPage" which will send the user to the task page endpoint

### Environment
Mac OS was tested with safari and chrome and Windows OS was tested with chrome. 

### Location
"http://localhost:2080/login"
"http://localhost:2080/Registration"
"http://localhost:2080/TaskPage"

### Expected behavior
The user can successfully create an account at the registration endpoint, which would take the user back to the login page where they may input their credentials, then access the task page.
### Observed behavior
Cannot create a new user (when filling out username and password to register a new account, the “Sign Up” button does not complete the task and page remains static). Also, the task page is blank and the login page triggers a 401 error in terminal that shows "no sessionID cookie".

### Console output/errors
*Relevant console output or errors, pasted as text.*
response error 401:
no sessionID cookie

### Screenshot
<img width="542" alt="Screenshot 2024-10-22 at 3 06 02 PM" src="https://github.com/user-attachments/assets/870e7f67-eb25-44fa-99f8-ab1dc13357c5">

<img width="861" alt="Screenshot 2024-10-22 at 10 57 22 AM" src="https://github.com/user-attachments/assets/b832644b-1516-4575-9707-2cd69c142087">

## Suggested fix
No immediate fixes known.

## Other notes
This may be more for GUI, though the registration endpoint has the text "OR REGISTER WITH" with line across it and the
login endpoint has the “DON’T HAVE AN ACCOUNT? SIGN UP” text displaced.

**Comment by estewar5** [comment]
Native Registration, that is, registration without Google/Github OAuth, is not currently implemented. If you were wishing to test Native Login, there is a sample email/password (email: user@gmail.com, password: password) that is in a placeholder database. This feature is anticipated for our next test-commit.

Please correct me if I am understanding this issue incorrectly as well.

**Comment by PiesArentSquare** [comment]
fixed sso login not available by #37

**Comment by PiesArentSquare** [comment]
fixed native registration
