### ISSUE TITLE
Task duplication on identical task name, date, and project when sorting

### ISSUE THREAD

**Issue by jbaile20** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#41]
## Problem
When saving changes with the same task title, date, and project, then using the sort button, the UI will continually add tasks to the screen, on refresh these disappear.

### Steps to reproduce

- Create 2 tasks with identical name, date, and project
- save tasks
- sort any column

### Environment
Windows
Google Chrome
gui-init branch - 526a749

*Subheadings below are optional; remove if not applicable.*
### Location
Main Task Page

### Expected behavior
Tasks should sort and tasks should not be able to be duplicated with the same name
### Observed behavior
Tasks duplicate continuously, and are removed on refresh

*Subheadings below are optional; remove if not applicable.*
### Console output/errors
Warning: Encountered two children with the same key, 0. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at tbody
    at table
    at div
    at TaskPage (http://localhost:2080/src/pages/TaskPage.jsx:60:29)
    at RenderedRoute (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=0106d8ca:4092:5)
    at Outlet (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=0106d8ca:4467:26)
    at main
    at PageLayout
    at RenderedRoute (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=0106d8ca:4092:5)
    at Routes (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=0106d8ca:4531:5)
    at Router (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=0106d8ca:4474:15)
    at BrowserRouter (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=0106d8ca:5219:5)
    at Component
printWarning @ chunk-6BKLQ22S.js?v=4518e5ca:521
error @ chunk-6BKLQ22S.js?v=4518e5ca:505
warnOnInvalidKey @ chunk-6BKLQ22S.js?v=4518e5ca:10219
reconcileChildrenArray @ chunk-6BKLQ22S.js?v=4518e5ca:10235
reconcileChildFibers2 @ chunk-6BKLQ22S.js?v=4518e5ca:10559
reconcileChildren @ chunk-6BKLQ22S.js?v=4518e5ca:14292
updateHostComponent @ chunk-6BKLQ22S.js?v=4518e5ca:14807
beginWork @ chunk-6BKLQ22S.js?v=4518e5ca:15935
beginWork$1 @ chunk-6BKLQ22S.js?v=4518e5ca:19753
performUnitOfWork @ chunk-6BKLQ22S.js?v=4518e5ca:19198
workLoopSync @ chunk-6BKLQ22S.js?v=4518e5ca:19137
renderRootSync @ chunk-6BKLQ22S.js?v=4518e5ca:19116
performConcurrentWorkOnRoot @ chunk-6BKLQ22S.js?v=4518e5ca:18678
workLoop @ chunk-6BKLQ22S.js?v=4518e5ca:197
flushWork @ chunk-6BKLQ22S.js?v=4518e5ca:176
performWorkUntilDeadline @ chunk-6BKLQ22S.js?v=4518e5ca:384
Show 16 more frames
Show lessUnderstand this errorAI

### Screenshot
![Issue #3](https://github.com/user-attachments/assets/eb64ed32-9fb8-425c-a667-a6368da07fa4)

## Other notes

*Remember to assign the issue exactly one severity label.*
medium/high

**Comment by s-Aura-v** [comment]
Fixed; Issue was caused by id duplication. All ids are unique now.
