### ISSUE TITLE
Correct UI elements on Task Page

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#50]
## Problem
Multiple UI errors on My Tasks Page

1. Task title names have no limit, in creation which covers the "Edit" pencil, (Advise allowing just selection of the task name field and limiting the number of characters for a task name)
2. Left column grey bar stops abruptly if the number of total tasks exceeds a certain limit. (7ish)
3. Logout Button moves into project panel
4. Color needs to change on the delete confirmation field when you are going over cancel.
5. Sort Icon appears underneath the header

### Steps to reproduce
1. Insert a title with a large amount of characters for the Task Title and enter

2. Save multiple tasks (7 or more) and scroll down

3. Zoom in to 150% and scroll, the "Log out" button scrolls with the screen.

4. On deleting a task, the confirmation "Cancel" is in black font rendering it unreadable when hovered. 

5. N/A

### Environment
*Browsers and operating systems on which the problem is known to occur.*

Google Chrome / Windows OS

*Subheadings below are optional; remove if not applicable.*
### Location
N/A Locally Hosted

### Expected behavior
*What we expect to happen.*
1, Task titles should either be limited or I should be able to directly select the task title.

2. Grey bar should continue down the left side regardless of task number.

3. Zoom should be dynamic for both the central and side items.

4. "Cancel" should be listed in white text on hover when a darker block appears over cancel.

5. "Sort" is underneath the column header areas.

### Observed behavior
*What actually happens.*
1, Task title takes the entire field and removed the ability to edit the title.

2. Grey bar on the left column doesn't continue down the page.

3. Central area should be dynamic up to 200%

4. "Cancel" is black text in a grey button

5. "Sort" should be to the right

### Screenshot
*Shows the incorrect behavior.*

![TaskName Extended](https://github.com/user-attachments/assets/62090af2-6e3f-4f35-83a0-9492a018e661)

![Log Out button moves with zoom%](https://github.com/user-attachments/assets/5ea951ec-e873-412f-88c3-7528b67522b1)

![Delete Task Font Color](https://github.com/user-attachments/assets/4602f774-4654-4986-867c-0d6011cb7c15)

![SortPage](https://github.com/user-attachments/assets/4af8b669-e12a-4980-93a5-38044c9d24c7)

**Comment by PiesArentSquare** [comment]
i think the last remaining issues have been fixed in e09a092ef6e92bd429ce94e2194af4031c016318
