### ISSUE TITLE
Semi-Functional Create/Delete Task

### ISSUE THREAD

**Issue by jaredball** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#56]
## Problem
This bug was found when creating and deleting tasks. When creating tasks, unique or not, all tasks are created with ID = 0. Due to this, clicking delete on any of the newly created tasks causes all of the new tasks to disappear. If the user refreshes, all of the new tasks now have unique IDs and the delete functionality works as intended.

### Steps to reproduce
1) Create X number of tasks (Observe Console error in inspect element)
2) Click the delete function on any of the new tasks (New tasks disappear)
3) Refresh
4) Delete functionality now works as intended

### Environment
This test was completed on a Mac using Google Chrome

### Expected behavior
Newly created tasks contain a unique ID and are able to be deleted
### Observed behavior
Newly created tasks contain ID = 0 and are not able to be deleted until the user refreshes the page

### Console output/errors
Warning: Encountered two children with the same key, `0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at tbody
    at table
    at div
    at TaskPage (http://localhost:2080/src/pages/TaskPage.jsx:62:29)
    at RenderedRoute (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=a2f0f117:4092:5)
    at Outlet (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=a2f0f117:4467:26)
    at main
    at PageLayout
    at RenderedRoute (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=a2f0f117:4092:5)
    at Routes (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=a2f0f117:4531:5)
    at Router (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=a2f0f117:4474:15)
    at BrowserRouter (http://localhost:2080/node_modules/.vite/deps/react-router-dom.js?v=a2f0f117:5219:5)
    at Component

### Screenshot
In the screen recording below, I was using the Save Changes button. I tested the Create New Task button as well but observed the same behavior since both use the Save Changes button in the end.

https://github.com/user-attachments/assets/4e889d4c-378b-4f12-9211-0f4be9a3177c

## Suggested fix
I do not have a big idea on the fix for this without the code in front of me but I do believe the root of the problem is that initial creation of tasks and the ID associated with that newly created task.

**Comment by s-Aura-v** [comment]
Fixed.

**Comment by jaredball** [comment]
I reopened this issue because delete still semi-functions. The issue now is that the tasks **do** delete, but only disappear on refresh. Otherwise, the tasks do hold unique ids and delete accordingly. Thanks!

**Comment by s-Aura-v** [comment]
Fixed as of most recent gui-init patch.

**Comment by jaredball** [comment]
Okay thanks Saurav I'll take a look

**Comment by jaredball** [comment]
Not quite working on my end, just checked out the most recent gui-init. **I am getting this on load:**

get: /projects
response error 401:

get: /tasks
response error 401:

get: /projects
response error 401:

get: /tasks
response error 401:

get: /projects
response error 401:

get: /projects
response error 401:

**And getting this when selecting "Save Changes":**

post: /tasks
response error 401:
