### ISSUE TITLE
Build Failure on Application Startup

### ISSUE THREAD

**Issue by Danpmas** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#75]
## Problem
When starting the application locally using the start_website script, an error message displays in terminal that says the auth-service failed to deploy.

### Steps to reproduce
1. Change directories to the project folder
2. run "bash start_website.sh" (Unix)
The "no cookie" notification at the bottom of the image provided below is assumed to be a byproduct of this error (replication this can be done by accessing localhost://2080 and attempting to login either through native logion or through GitHub).

### Environment
*Browsers and operating systems on which the problem is known to occur.*
OS: Mac (Apple Silicon)
Browser: Chrome

### Location
In Terminal ("no cookie" error was through localhost://2080)

### Expected behavior
The application should launch with all three services successful. 
### Observed behavior
Auth-service does not launch successfully.

### Console output/errors
[INFO]
BUILD FAILURE
[INFO] [INFO] [INFO]
Total time: 49.937 s
Finished at: 2024-11-1107:38:23-05:00
[INFO]
[ERROR]
Failed to execute goal io.openliberty.tools:liberty-maven-plugin:3.10.3:dev (default-cli) on project database-service:
CWWKM2187E: Failed to deploy the database-service application. The application start message was not found in the log file. -›
[Help 1]
[ERROR] [ERROR]
[ERROR]
To see the full
stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.
[ERROR] [ERROR]
For more
information about the errors
and possible solutions, please read the following articles:
[ERROR]
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
no cookie

### Screenshot
<img width="967" alt="Screenshot 2024-11-11 at 7 41 18 AM" src="https://github.com/user-attachments/assets/dbde7ddd-9ece-4ecb-b791-4ac90a9f7a6b">

## Suggested fix
N/A

## Other notes

*Remember to assign the issue exactly one severity label.*

**Comment by PiesArentSquare** [comment]
unable to replicate on newer commits, so it was probably just a transitive bug

**Comment by SmartGarlic** [comment]
@Danpmas - Can you validate that this is closed at this point on your end? If so let's close this issue out.

**Comment by Danpmas** [comment]
Yes this can be closed, I apologize I didn't close it sooner.
