### ISSUE TITLE
Date / Priority not displayed in task list

### ISSUE THREAD

**Issue by SmartGarlic** [Paul-Austin-Oswego-CSC480-HCI521/OZ-CSC-480-HCI-521-Fall-2024#79]
## Problem
*A clear description of the defect or bug.*
When adding a task the dates and priorities are not displayed in the list view of the content. These are blank due dates here and priority but on refresh, the tabs fill with No Due Date, Medium Priority and unknown projects.

### Steps to reproduce
- Create a task with any date or priority
- Refresh the page

### Environment
*Browsers and operating systems on which the problem is known to occur.*
Chrome - Windows

*Subheadings below are optional; remove if not applicable.*
### Location
*URL(s) where the bug occurs.*
http://moxie.cs.oswego.edu:49000/ 

### Screenshot
![NoDueDateorPriorityDisplayed](https://github.com/user-attachments/assets/0dbd2668-da88-4f01-8bbc-04c9dc524ca1)
![RefreshNoDueDate](https://github.com/user-attachments/assets/ab5e5571-5f46-4ca4-bf15-b4da46b30843)

## Other notes
*Anything that could be informative, and doesn't fit anywhere else.*

**Comment by s-Aura-v** [comment]
Added; It is part of the latest version of gui-init.
